#pragma once

#include "genseki/core/hex.hpp"
#include "genseki/core/piece.hpp"

#include <array>
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <initializer_list>
#include <optional>
#include <string>
#include <string_view>
#include <stdexcept>
#include <vector>

namespace genseki {

#ifdef GENSEKI_NU_CANCELLATION
// Enabled only in Nu's separately compiled rules library.
inline thread_local void (*nu_generation_check)(void*) = nullptr;
inline thread_local void* nu_generation_context = nullptr;
inline void check_nu_generation() { if(nu_generation_check)nu_generation_check(nu_generation_context); }

// One bottom piece plus the four Base-Hive Beetles; no heap allocation.
class NuPieceStack {
    std::array<Piece,5> data_{};
    std::uint8_t count_=0;
public:
    NuPieceStack()=default;
    NuPieceStack(std::initializer_list<Piece> pieces){for(auto piece:pieces)push_back(piece);}
    std::size_t size()const{return count_;}
    bool empty()const{return count_==0;}
    Piece* begin(){return data_.data();}
    Piece* end(){return begin()+count_;}
    const Piece* begin()const{return data_.data();}
    const Piece* end()const{return begin()+count_;}
    Piece& operator[](std::size_t i){return data_[i];}
    const Piece& operator[](std::size_t i)const{return data_[i];}
    Piece& back(){if(empty())throw std::logic_error("empty Nu stack");return data_[count_-1];}
    const Piece& back()const{if(empty())throw std::logic_error("empty Nu stack");return data_[count_-1];}
    void push_back(Piece piece){if(count_==data_.size())throw std::logic_error("Base Hive stack exceeds five pieces");data_[count_++]=piece;}
    void pop_back(){if(empty())throw std::logic_error("empty Nu stack");--count_;}
    bool operator==(const NuPieceStack& other)const{return count_==other.count_&&std::equal(begin(),end(),other.begin());}
    auto operator<=>(const NuPieceStack& other)const{return std::lexicographical_compare_three_way(begin(),end(),other.begin(),other.end());}
};
#endif

struct Stack {
    Hex cell{};
#ifdef GENSEKI_NU_CANCELLATION
    NuPieceStack pieces{};
#else
    std::vector<Piece> pieces{};
#endif
    auto operator<=>(const Stack&) const = default;
};

enum class MoveKind : std::uint8_t { placement, movement, pass };

struct Move {
    MoveKind kind = MoveKind::placement;
    std::optional<Hex> from{};
    Hex to{};
    Piece piece{};
    auto operator<=>(const Move&) const = default;
};

enum class GameResult : std::uint8_t { ongoing, white_win, black_win, draw };
enum class MoveError : std::uint8_t { game_over, illegal_move };

struct Undo {
    Move move{};
    Color previous_side = Color::white;
    std::size_t previous_ply = 0;
    std::array<std::size_t, 2> previous_turns{};
    std::size_t previous_history_size = 0;
};

[[nodiscard]] std::string move_notation(const Move& move);
[[nodiscard]] std::expected<Move, std::string> parse_move(std::string_view text);
[[nodiscard]] std::string_view name(GameResult result);
[[nodiscard]] std::string_view name(MoveError error);

class Board {
public:
    [[nodiscard]] Color side_to_move() const;
    [[nodiscard]] std::size_t ply() const;
    [[nodiscard]] const std::vector<Stack>& stacks() const;
    [[nodiscard]] const std::vector<Move>& history() const;
    [[nodiscard]] std::vector<Move> legal_moves() const;
#ifdef GENSEKI_NU_CANCELLATION
    [[nodiscard]] std::vector<Move> movement_moves(Color color, std::optional<Hex> only = std::nullopt) const;
    [[nodiscard]] Board with_side_to_move(Color color) const;
#endif
    [[nodiscard]] bool is_legal(const Move& move) const;
    [[nodiscard]] bool is_terminal() const;
    [[nodiscard]] GameResult result() const;
    [[nodiscard]] std::string summary() const;
    [[nodiscard]] std::string position_string() const;
    [[nodiscard]] std::string game_string() const;
    [[nodiscard]] std::expected<std::string, std::string> uhp_move_string(const Move& move) const;
    // Precondition: move came from legal_moves() for this exact board.
    [[nodiscard]] std::expected<std::string, std::string> generated_uhp_move_string(const Move& move) const;
    [[nodiscard]] std::expected<Move, std::string> parse_uhp_move(std::string_view text) const;

    [[nodiscard]] std::expected<void, MoveError> play(const Move& move);
    [[nodiscard]] std::expected<Undo, MoveError> make_move(const Move& move);
    // Precondition: move was generated by legal_moves() for this exact position.
    [[nodiscard]] Undo make_generated_move(const Move& move);
    void unmake_move(const Undo& undo);
    [[nodiscard]] std::uint64_t perft(unsigned depth);
    [[nodiscard]] bool undo(unsigned count = 1);

    [[nodiscard]] static std::expected<Board, std::string> from_position_string(std::string_view text);
    [[nodiscard]] static std::expected<Board, std::string> from_game_string(std::string_view text);

private:
    Color side_to_move_ = Color::white;
    std::size_t ply_ = 0;
    std::vector<Stack> stacks_{};
    std::array<std::size_t, 2> turns_taken_{0, 0};
    std::vector<Move> history_{};
#ifdef GENSEKI_NU_CANCELLATION
    mutable std::array<int,64> cell_index_{};
    mutable std::size_t indexed_size_=0;
    mutable bool index_ready_=false;
    [[nodiscard]] std::optional<std::size_t> indexed_cell(Hex cell) const;
#endif

    [[nodiscard]] const Stack* stack_at(Hex cell) const;
    [[nodiscard]] Stack* stack_at(Hex cell);
    [[nodiscard]] bool occupied(Hex cell) const;
    [[nodiscard]] std::size_t height(Hex cell) const;
    [[nodiscard]] std::vector<Hex> placement_cells() const;
    [[nodiscard]] std::vector<Piece> pieces_in_hand(Color color) const;
    [[nodiscard]] bool queen_played(Color color) const;
    [[nodiscard]] std::optional<Hex> queen_cell(Color color) const;
    [[nodiscard]] bool hive_connected_after_lift(Hex cell) const;
    [[nodiscard]] bool touches_hive(Hex cell) const;
    [[nodiscard]] bool can_slide(Hex from, Hex to) const;
    [[nodiscard]] bool beetle_gate_open(Hex from, Hex to, std::size_t source_height) const;
    [[nodiscard]] std::vector<Hex> movement_destinations(Hex from, const Piece& piece) const;
    [[nodiscard]] std::vector<Hex> ground_crawl(Hex start, bool exactly_three) const;

    void apply_unchecked(const Move& move);
    void undo_unchecked(const Undo& undo);
    void normalize_stacks();
};

}  // namespace genseki
